sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: upmin_admin_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: <%= `whoami`.strip %>
  password:
  database: upmin_admin_<%= Rails.env %>
  encoding: unicode

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['TEST_DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults
